
// This file has been generated by the GUI designer. Do not modify.
namespace CashFlow
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action HakkndaAction;

		private global::Gtk.Action HakkndaAction1;

		private global::Gtk.VBox MainVbox;

		private global::Gtk.MenuBar menubar2;

		private global::Gtk.HBox PropsVbox;

		private global::Gtk.Frame DateFrame;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.Table DateFrameTable;

		private global::Gtk.Entry DateEndEntry;

		private global::Gtk.Label DateEndLabel;

		private global::Gtk.Entry DateStartEntry;

		private global::Gtk.Label DateStartLabel;

		private global::Gtk.Label DateFrameLabel1;

		private global::Gtk.Frame CurrencyFrame;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.VBox CurrencyVbox;

		private global::Gtk.HBox CurrencyHbox;

		private global::Gtk.Label CurrencyBaseLabel;

		private global::Gtk.ComboBox CurrencyBaseSelection;

		private global::Gtk.Button CurrencyListButton;

		private global::Gtk.Label CurrencyFrameLabel;

		private global::Gtk.Button FetchButton;

		private global::Gtk.Alignment MainPlotAlignment;

		private global::Gtk.Statusbar MainStatusBar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CashFlow.MainWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.HakkndaAction = new global::Gtk.Action("HakkndaAction", global::Mono.Unix.Catalog.GetString("Hakkında"), null, null);
			this.HakkndaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Hakkında");
			w1.Add(this.HakkndaAction, null);
			this.HakkndaAction1 = new global::Gtk.Action("HakkndaAction1", global::Mono.Unix.Catalog.GetString("Hakkında"), null, null);
			this.HakkndaAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Hakkında");
			w1.Add(this.HakkndaAction1, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "CashFlow.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("CashFlow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 1280;
			this.DefaultHeight = 720;
			// Container child CashFlow.MainWindow.Gtk.Container+ContainerChild
			this.MainVbox = new global::Gtk.VBox();
			this.MainVbox.Name = "MainVbox";
			this.MainVbox.Spacing = 6;
			// Container child MainVbox.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar2\'><menu name=\'HakkndaAction1\' action=\'HakkndaAction1\'/" +
					"></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.MainVbox.Add(this.menubar2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MainVbox[this.menubar2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child MainVbox.Gtk.Box+BoxChild
			this.PropsVbox = new global::Gtk.HBox();
			this.PropsVbox.Name = "PropsVbox";
			this.PropsVbox.Spacing = 6;
			// Container child PropsVbox.Gtk.Box+BoxChild
			this.DateFrame = new global::Gtk.Frame();
			this.DateFrame.Name = "DateFrame";
			this.DateFrame.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child DateFrame.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			this.GtkAlignment.TopPadding = ((uint)(6));
			this.GtkAlignment.RightPadding = ((uint)(6));
			this.GtkAlignment.BottomPadding = ((uint)(6));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.DateFrameTable = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.DateFrameTable.Name = "DateFrameTable";
			this.DateFrameTable.RowSpacing = ((uint)(6));
			this.DateFrameTable.ColumnSpacing = ((uint)(6));
			// Container child DateFrameTable.Gtk.Table+TableChild
			this.DateEndEntry = new global::Gtk.Entry();
			this.DateEndEntry.CanFocus = true;
			this.DateEndEntry.Name = "DateEndEntry";
			this.DateEndEntry.Text = global::Mono.Unix.Catalog.GetString("-tarih seçin-");
			this.DateEndEntry.IsEditable = false;
			this.DateEndEntry.InvisibleChar = '•';
			this.DateFrameTable.Add(this.DateEndEntry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.DateFrameTable[this.DateEndEntry]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child DateFrameTable.Gtk.Table+TableChild
			this.DateEndLabel = new global::Gtk.Label();
			this.DateEndLabel.Name = "DateEndLabel";
			this.DateEndLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Bitiş:");
			this.DateFrameTable.Add(this.DateEndLabel);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.DateFrameTable[this.DateEndLabel]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child DateFrameTable.Gtk.Table+TableChild
			this.DateStartEntry = new global::Gtk.Entry();
			this.DateStartEntry.CanFocus = true;
			this.DateStartEntry.Name = "DateStartEntry";
			this.DateStartEntry.Text = global::Mono.Unix.Catalog.GetString("-tarih seçin-");
			this.DateStartEntry.IsEditable = false;
			this.DateStartEntry.InvisibleChar = '•';
			this.DateFrameTable.Add(this.DateStartEntry);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.DateFrameTable[this.DateStartEntry]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child DateFrameTable.Gtk.Table+TableChild
			this.DateStartLabel = new global::Gtk.Label();
			this.DateStartLabel.Name = "DateStartLabel";
			this.DateStartLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Başlangıç:");
			this.DateFrameTable.Add(this.DateStartLabel);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.DateFrameTable[this.DateStartLabel]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add(this.DateFrameTable);
			this.DateFrame.Add(this.GtkAlignment);
			this.DateFrameLabel1 = new global::Gtk.Label();
			this.DateFrameLabel1.Name = "DateFrameLabel1";
			this.DateFrameLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Tarih Aralığı</b>");
			this.DateFrameLabel1.UseMarkup = true;
			this.DateFrame.LabelWidget = this.DateFrameLabel1;
			this.PropsVbox.Add(this.DateFrame);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.PropsVbox[this.DateFrame]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child PropsVbox.Gtk.Box+BoxChild
			this.CurrencyFrame = new global::Gtk.Frame();
			this.CurrencyFrame.Name = "CurrencyFrame";
			this.CurrencyFrame.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child CurrencyFrame.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			this.GtkAlignment1.TopPadding = ((uint)(6));
			this.GtkAlignment1.RightPadding = ((uint)(6));
			this.GtkAlignment1.BottomPadding = ((uint)(6));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.CurrencyVbox = new global::Gtk.VBox();
			this.CurrencyVbox.Name = "CurrencyVbox";
			// Container child CurrencyVbox.Gtk.Box+BoxChild
			this.CurrencyHbox = new global::Gtk.HBox();
			this.CurrencyHbox.Name = "CurrencyHbox";
			this.CurrencyHbox.Spacing = 6;
			// Container child CurrencyHbox.Gtk.Box+BoxChild
			this.CurrencyBaseLabel = new global::Gtk.Label();
			this.CurrencyBaseLabel.Name = "CurrencyBaseLabel";
			this.CurrencyBaseLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Taban Kur:");
			this.CurrencyHbox.Add(this.CurrencyBaseLabel);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.CurrencyHbox[this.CurrencyBaseLabel]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child CurrencyHbox.Gtk.Box+BoxChild
			this.CurrencyBaseSelection = global::Gtk.ComboBox.NewText();
			this.CurrencyBaseSelection.Name = "CurrencyBaseSelection";
			this.CurrencyHbox.Add(this.CurrencyBaseSelection);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.CurrencyHbox[this.CurrencyBaseSelection]));
			w11.Position = 1;
			this.CurrencyVbox.Add(this.CurrencyHbox);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.CurrencyVbox[this.CurrencyHbox]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child CurrencyVbox.Gtk.Box+BoxChild
			this.CurrencyListButton = new global::Gtk.Button();
			this.CurrencyListButton.CanFocus = true;
			this.CurrencyListButton.Name = "CurrencyListButton";
			this.CurrencyListButton.UseUnderline = true;
			this.CurrencyListButton.Label = global::Mono.Unix.Catalog.GetString("Gösterilecek Kurlar");
			this.CurrencyVbox.Add(this.CurrencyListButton);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.CurrencyVbox[this.CurrencyListButton]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.GtkAlignment1.Add(this.CurrencyVbox);
			this.CurrencyFrame.Add(this.GtkAlignment1);
			this.CurrencyFrameLabel = new global::Gtk.Label();
			this.CurrencyFrameLabel.Name = "CurrencyFrameLabel";
			this.CurrencyFrameLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Kur Tercihleri</b>");
			this.CurrencyFrameLabel.UseMarkup = true;
			this.CurrencyFrame.LabelWidget = this.CurrencyFrameLabel;
			this.PropsVbox.Add(this.CurrencyFrame);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.PropsVbox[this.CurrencyFrame]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child PropsVbox.Gtk.Box+BoxChild
			this.FetchButton = new global::Gtk.Button();
			this.FetchButton.CanFocus = true;
			this.FetchButton.Name = "FetchButton";
			this.FetchButton.UseUnderline = true;
			this.FetchButton.Label = global::Mono.Unix.Catalog.GetString("Verileri Getir");
			this.PropsVbox.Add(this.FetchButton);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.PropsVbox[this.FetchButton]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.MainVbox.Add(this.PropsVbox);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.MainVbox[this.PropsVbox]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child MainVbox.Gtk.Box+BoxChild
			this.MainPlotAlignment = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.MainPlotAlignment.Name = "MainPlotAlignment";
			this.MainVbox.Add(this.MainPlotAlignment);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.MainVbox[this.MainPlotAlignment]));
			w19.Position = 2;
			// Container child MainVbox.Gtk.Box+BoxChild
			this.MainStatusBar = new global::Gtk.Statusbar();
			this.MainStatusBar.Name = "MainStatusBar";
			this.MainStatusBar.Spacing = 6;
			this.MainVbox.Add(this.MainStatusBar);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.MainVbox[this.MainStatusBar]));
			w20.PackType = ((global::Gtk.PackType)(1));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			this.Add(this.MainVbox);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.DateStartEntry.FocusGrabbed += new global::System.EventHandler(this.OnDateStartEntryFocusGrabbed);
			this.DateEndEntry.FocusGrabbed += new global::System.EventHandler(this.OnDateEndEntryFocusGrabbed);
			this.CurrencyBaseSelection.Changed += new global::System.EventHandler(this.OnCurrencyBaseSelectionChanged);
			this.CurrencyListButton.Clicked += new global::System.EventHandler(this.OnCurrencyListButtonClicked);
			this.FetchButton.Clicked += new global::System.EventHandler(this.OnFetchButtonClicked);
		}
	}
}
